# -*- coding: utf-8 -*-
"""14301172022_TANISHA_BANSAL_ASSIGNMENT-2_DL_CSE-AI-2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zfvibK-6Qy6o3S3QV7xwrZT5FEELL9Iz

**SUBMITTED BY:-**

**NAME:-** TANISHA BANSAL

**BRANCH:-** CSE-AI-2

**ROLL NO:-** 14301172022

**SUBMISSION DATE:-** 25th August 2024

**COURSE:-** DEEP LEARNING ASSIGNMENT - 2

**AIM:** Write a program using Pandas library to create and display data frames from a
CSV and explore the functionalities of dataframes.

**(i) Loading and Printing first ten rows of dataset**
"""

import pandas as pd

# Loading the dataset
data = pd.read_csv('Automobile_data.csv')

# Printing the first ten rows
print(data.head(10))

"""**(ii) Dropping a column**"""

# Dropping the 'length' column
dropped_data = data.drop(columns=['length'])

# Printing the dataframe after dropping the column
print(dropped_data.head())

"""**(iii) Printing last five rows**"""

# Printing the last five rows
print(data.tail(5))

"""**(iv) Print All Toyota Cars details**"""

# Printing all rows where the company is 'Toyota'
toyota_cars = data[data['company'] == 'Toyota']
print(toyota_cars)

"""**(v) Count total cars per company**"""

# Counting total cars per company
counts_of_cars = data['company'].value_counts()
print(counts_of_cars)

"""**(vi) Find each company’s Highest price car**"""

# Finding each company’s highest price car
highest_price_car = data.groupby('company')['price'].max()
print(highest_price_car)

"""**(vii) Getting average mileage of car**"""

# Calculating average mileage of all cars
average_mileage = data['average-mileage'].mean()
print(f"Average mileage of all cars: {average_mileage}")

"""**(viii) Sort all cars by Price column**"""

# Sorting all cars by the 'price' column
sorting_cars = data.sort_values(by='price', ascending=True)
print(sorting_cars)